name: Deploy EPG Guide

on:
  - cron: "0 2 * * *" # Runs at 2:00 AM UTC every day
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate EPG Guide
        run: npm run make-guide

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare artifact
        run: |
          mkdir -p ./tmp/data
          cp ./assets/data/epg-guide.json ./tmp/data/
          cp ./public/index.html ./tmp/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./tmp"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
